name: .NET Build and Test

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: workflow-azure
    tags:
      - "v*.*.*"
  pull_request:
    branches: azure

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Create ZIP files
        run: |
          # Create a release directory to hold all platform-specific releases
          mkdir release

          # Publish for Linux (default)
          dotnet publish -c Release -o ./release/linux
          cd release/linux
          zip -r ../../my_project_linux.zip .

          # Publish for macOS
          cd ../../
          dotnet publish -r osx-x64 -c Release -o ./release/mac
          cd release/mac
          zip -r ../../my_project_mac.zip .

          # Publish for Windows
          cd ../../
          dotnet publish -r win-x64 -c Release -o ./release/win
          cd release/win
          zip -r ../../my_project_win.zip .

     ## - name: GH Release
        ##uses: softprops/action-gh-release@v2.0.8
      ##  with:
        ##  files: |
          ##  my_project_linux.zip
            ##my_project_mac.zip
            ##my_project_win.zip


deploy:
  runs-on: ubuntu-latest
  needs: build
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  permissions:
    id-token: write #This is required for requesting the JWT
  
  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EDDC0F0EF9DB4770B08C1775416ED4FB }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E2E7DFF2BE0F43A39820045011F70A2E }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_308084345AC04BD8B3695AB012974585 }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'bdsagroup16chirpremotedb'
        slot-name: 'Production'
        package: .
          