name: .NET Build and Test

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: workflow-fixing
    tags:
      - "v*.*.*"
  pull_request:
    branches: workflow-fixing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Create ZIP file
        run: |
          mkdir release
          dotnet publish -c Release -o ./release
          cd release
          zip -r ../my_project.zip .  # Change 'my_project.zip' to your desired ZIP file name
      - name: GH Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: my_project.zip  # Specify the ZIP file to be attached to the release
